# Generated by Django 3.1.7 on 2021-04-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_name', models.CharField(max_length=25, unique=True)),
                ('move_strength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('points', models.IntegerField()),
                ('friendlist', models.ManyToManyField(related_name='_user_friendlist_+', to='pokinaturalist.User')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.IntegerField()),
                ('item_strength', models.IntegerField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokinaturalist.user')),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('observation_base', models.CharField(max_length=200)),
                ('strength', models.IntegerField()),
                ('moveset', models.ManyToManyField(to='pokinaturalist.Move')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokinaturalist.user')),
            ],
        ),
    ]
